#!/usr/bin/env node
/**
 * patch-site.mjs — Lighthouse patch for a Next.js (Turbopack) site.
 *
 * Usage (from project root):
 *   node patch-site.mjs           # DRY RUN: shows what would change, writes nothing
 *   node patch-site.mjs --apply   # applies changes, backups go to .perf-backup/<timestamp>/
 *
 * What it does automatically (safe + idempotent):
 *   1. Creates perf-headers.mjs  (cache headers for public assets + security headers)
 *   2. Wires it into next.config.* via `headers()` (or tells you how if it can't)
 *   3. Creates HeroVideo component (poster-first, deferred video, captions track)
 *   4. Creates public/captions-empty.vtt
 * What it only REPORTS (needs your eyes, can't be safely automated):
 *   - Google Fonts <link>/@import, <img> without lazy/size, <video> usage, http:// URLs
 *   - Oversized images / video in public/
 */
import fs from 'node:fs';
import path from 'node:path';

const APPLY = process.argv.includes('--apply');
const root = process.cwd();
const log = (...a) => console.log(...a);
const stamp = new Date().toISOString().replace(/[:.]/g, '-');
const backupDir = path.join(root, '.perf-backup', stamp);

function backup(f) {
  if (!APPLY || !fs.existsSync(f)) return;
  const d = path.join(backupDir, path.relative(root, f));
  fs.mkdirSync(path.dirname(d), { recursive: true });
  fs.copyFileSync(f, d);
}
function writeNew(rel, content) {
  const f = path.join(root, rel);
  if (fs.existsSync(f)) { log(`  skip   ${rel} (already exists)`); return; }
  log(`  ${APPLY ? 'write ' : 'would write'} ${rel}`);
  if (APPLY) { fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, content); }
}

// ───────────────────────── 0. Sanity checks ─────────────────────────
log(`\n== patch-site (${APPLY ? 'APPLY' : 'DRY RUN'}) ==\n`);
const pkgPath = path.join(root, 'package.json');
if (!fs.existsSync(pkgPath)) { console.error('No package.json here. Run from your project root.'); process.exit(1); }
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
const nextVer = pkg.dependencies?.next || pkg.devDependencies?.next;
if (!nextVer) { console.error('"next" not found in package.json — this script targets Next.js.'); process.exit(1); }
log(`Next.js: ${nextVer}`);
const hasApp = fs.existsSync(path.join(root, 'app')) || fs.existsSync(path.join(root, 'src/app'));
log(`Router : ${hasApp ? 'App Router' : 'Pages Router (or unknown)'}\n`);

// ───────────────────────── 1. perf-headers.mjs ─────────────────────────
log('[1] Headers file');
const HEADERS_FILE = `// Generated by patch-site.mjs — edit freely.
// CSP_MODE: 'report-only' (safe default, logs violations in DevTools console)
//           'enforce'     (switch ONLY after the console shows zero violations)
//           'off'
const CSP_MODE = 'report-only';
const isProd = process.env.NODE_ENV === 'production';

// NOTE: Next.js needs 'unsafe-inline' for its inline bootstrap scripts unless you use nonces
// (middleware/proxy). A nonce-based CSP is the only way to fully satisfy Lighthouse's
// "CSP effective against XSS" check, but it forces dynamic rendering — a real tradeoff.
// If you still use Google Fonts via <link>, add https://fonts.googleapis.com to style-src
// and https://fonts.gstatic.com to font-src (better: migrate to next/font and remove them).
const csp = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'" + (isProd ? '' : " 'unsafe-eval'"),
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "media-src 'self'",
  "font-src 'self' data:",
  "connect-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'self'",
].join('; ');

export default async function headers() {
  const security = [
    { key: 'X-Content-Type-Options', value: 'nosniff' },
    { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
    { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
    { key: 'Cross-Origin-Opener-Policy', value: 'same-origin' },
    { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
  ];
  // HSTS is ignored over plain http, and is sticky once the browser sees it over https.
  // No "preload" and no "includeSubDomains" on purpose — add them only when you're sure.
  if (isProd) security.push({ key: 'Strict-Transport-Security', value: 'max-age=31536000' });
  if (CSP_MODE === 'enforce') security.push({ key: 'Content-Security-Policy', value: csp });
  if (CSP_MODE === 'report-only') security.push({ key: 'Content-Security-Policy-Report-Only', value: csp });

  return [
    { source: '/:path*', headers: security },
    {
      // Unhashed files in /public: 30 days. If you replace a file, RENAME it (s1.webp -> s1.v2.webp)
      // or users will see the old one for up to 30 days.
      source: '/:all*(webp|avif|png|jpg|jpeg|gif|svg|ico|mp4|webm)',
      headers: [{ key: 'Cache-Control', value: 'public, max-age=2592000, stale-while-revalidate=86400' }],
    },
  ];
}
`;
writeNew('perf-headers.mjs', HEADERS_FILE);

// ───────────────────────── 2. Wire into next.config ─────────────────────────
log('\n[2] next.config wiring');
const cfgName = ['next.config.ts', 'next.config.mjs', 'next.config.js', 'next.config.cjs']
  .find((n) => fs.existsSync(path.join(root, n)));
const INSERT = `\n  async headers() {\n    const { default: perfHeaders } = await import('./perf-headers.mjs'); // added by patch-site\n    return perfHeaders();\n  },`;
const MANUAL = `  Add this inside your config object manually:${INSERT}`;
if (!cfgName) {
  log('  No next.config.* found.');
  writeNew('next.config.mjs', `/** @type {import('next').NextConfig} */\nconst nextConfig = {${INSERT}\n};\nexport default nextConfig;\n`);
} else {
  const f = path.join(root, cfgName);
  const src = fs.readFileSync(f, 'utf8');
  if (src.includes('perf-headers')) log(`  skip   ${cfgName} (already wired)`);
  else if (/\bheaders\s*\(/.test(src)) log(`  WARN   ${cfgName} already defines headers(). Not touching it.\n  Merge the array returned by perf-headers.mjs into yours.`);
  else {
    const re = /((?:const|let|var)\s+\w+(?:\s*:\s*[\w.<>]+)?\s*=\s*\{|export\s+default\s*\{|module\.exports\s*=\s*\{)/;
    if (!re.test(src)) log(`  WARN   couldn't find the config object in ${cfgName}.\n${MANUAL}`);
    else {
      log(`  ${APPLY ? 'patch ' : 'would patch'} ${cfgName}`);
      if (APPLY) { backup(f); fs.writeFileSync(f, src.replace(re, (m) => m + INSERT)); }
    }
  }
}

// ───────────────────────── 3. HeroVideo + captions ─────────────────────────
log('\n[3] HeroVideo component');
const compDir = fs.existsSync(path.join(root, 'src')) ? 'src/components' : 'components';
const HERO = `'use client';
import { useEffect, useState } from 'react';

type Props = { src: string; poster: string; className?: string };

/**
 * Poster <img> is server-rendered => browser discovers the LCP image from the HTML immediately
 * (fixes "LCP request discovery"). The 900KB video loads only AFTER window load, only on
 * desktop-width screens, and never for reduced-motion / Save-Data / 2G users.
 * Parent should be position:relative with a set height (e.g. h-screen).
 */
export default function HeroVideo({ src, poster, className }: Props) {
  const [play, setPlay] = useState(false);

  useEffect(() => {
    const conn = (navigator as any).connection;
    const saveData = conn?.saveData || /(^|-)2g$/.test(conn?.effectiveType || '');
    const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const wide = window.matchMedia('(min-width: 768px)').matches;
    if (saveData || reduce || !wide) return;
    const start = () => setTimeout(() => setPlay(true), 150);
    if (document.readyState === 'complete') start();
    else window.addEventListener('load', start, { once: true });
    return () => window.removeEventListener('load', start);
  }, []);

  const fill: React.CSSProperties = { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' };

  return (
    <div className={className} aria-hidden="true">
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={poster} alt="" fetchPriority="high" decoding="async" style={fill} />
      {play && (
        <video src={src} poster={poster} autoPlay muted loop playsInline preload="auto" tabIndex={-1} style={fill}>
          <track kind="captions" src="/captions-empty.vtt" srcLang="en" label="No dialogue" />
        </video>
      )}
    </div>
  );
}
`;
writeNew(`${compDir}/HeroVideo.tsx`, HERO);
writeNew('public/captions-empty.vtt', 'WEBVTT\n\n');

// ───────────────────────── 4. Scan source (report only) ─────────────────────────
log('\n[4] Source scan (report only — review each by hand)');
const SKIP = new Set(['node_modules', '.next', '.git', '.perf-backup', 'out', 'dist']);
const EXT = /\.(tsx|jsx|ts|js|mjs|css|scss|html|mdx)$/;
const rules = [
  { re: /fonts\.googleapis\.com|@import\s+url\([^)]*fonts/i, msg: 'Google Fonts via CSS -> switch to next/font/google (removes render-blocking CSS + gstatic chain)' },
  { re: /<img\b(?![^>]*\bloading=)/, msg: '<img> without loading= -> loading="lazy" on below-the-fold images; add width/height' },
  { re: /<video\b/, msg: '<video> -> use HeroVideo (poster, deferred load, captions track)' },
  { re: /<a\b[^>]*target=["']_blank["'](?![^>]*\brel=)/, msg: 'target=_blank without rel -> add rel="noopener noreferrer"' },
  { re: /["'`]http:\/\/(?!www\.w3\.org|localhost|127\.0\.0\.1)/, msg: 'hard-coded http:// URL -> use https:// (mixed content once site is on HTTPS)' },
  { re: /\bpriority\b/, msg: 'priority prop found (ok if it is on exactly ONE hero image)' },
];
let findings = 0;
(function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP.has(e.name)) continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) { if (!/^public$/.test(e.name)) walk(p); continue; }
    if (!EXT.test(e.name) || e.name === 'patch-site.mjs' || e.name === 'perf-headers.mjs') continue;
    fs.readFileSync(p, 'utf8').split('\n').forEach((line, i) => {
      for (const r of rules) if (r.re.test(line)) { findings++; log(`  ${path.relative(root, p)}:${i + 1}\n      ${r.msg}`); }
    });
  }
})(root);
if (!findings) log('  nothing flagged');

// ───────────────────────── 5. Public asset audit ─────────────────────────
log('\n[5] public/ asset audit');
let sharp = null;
try { sharp = (await import('sharp')).default; } catch { log('  (sharp not found — sizes only, no dimensions)'); }
const pub = path.join(root, 'public');
if (fs.existsSync(pub)) {
  for (const name of fs.readdirSync(pub).sort()) {
    const p = path.join(pub, name);
    if (!fs.statSync(p).isFile()) continue;
    const kb = fs.statSync(p).size / 1024;
    let note = '';
    if (/\.(webp|png|jpe?g|avif)$/i.test(name)) {
      let dim = '';
      if (sharp) { try { const m = await sharp(p).metadata(); dim = `${m.width}x${m.height}`; if (m.width > 1600) note += ' <- wider than any phone/laptop needs; resize to <=1600w (<=800w for cards)'; } catch {} }
      if (kb > 100) note += ' <- >100KB';
      if (/\.png$/i.test(name) && kb > 5) note += ' <- consider webp/svg';
      log(`  ${name.padEnd(28)} ${kb.toFixed(1).padStart(8)} KB  ${dim}${note}`);
    } else if (/\.(mp4|webm)$/i.test(name)) {
      log(`  ${name.padEnd(28)} ${kb.toFixed(1).padStart(8)} KB  ${kb > 500 ? '<- re-encode (see ffmpeg commands below)' : ''}`);
    }
  }
} else log('  no public/ dir');

// ───────────────────────── Next steps ─────────────────────────
log(`
== MANUAL STEPS (the script can't do these safely) ==
 A. HTTPS (biggest Best-Practices win): serve the site over HTTPS + redirect http->https + HTTP/2.
    Your run says "20 insecure requests", i.e. the page itself was served over http.
 B. Fonts: replace the Google Fonts <link> with next/font/google (snippet in chat).
 C. Hero: swap your <video> for <HeroVideo src="/mhero-30.mp4" poster="/hero-poster.webp" />.
    Create the poster + shrink the video:
      ffmpeg -i public/mhero-30.mp4 -frames:v 1 -vf scale=1280:-2 hero-poster.png
      npx sharp-cli -i hero-poster.png -o public/hero-poster.webp -f webp -q 70   # or any png->webp tool
      ffmpeg -i public/mhero-30.mp4 -an -vf "scale='min(1280,iw)':-2" -c:v libx264 -crf 29 -preset slow -movflags +faststart public/mhero-30.new.mp4
    Compare the sizes, then rename mhero-30.new.mp4 -> mhero-30.v2.mp4 and update src.
 D. Test on a PRODUCTION build in an incognito window:  npm run build && npm start
 E. After applying: open DevTools Console for CSP-Report-Only violations. Fix them, THEN set CSP_MODE='enforce'.
${APPLY ? '' : '\nThis was a DRY RUN. Re-run with --apply to write changes.\n'}`);
