// Generated by patch-site.mjs — edit freely.
// CSP_MODE: 'report-only' (safe default, logs violations in DevTools console)
//           'enforce'     (switch ONLY after the console shows zero violations)
//           'off'
const CSP_MODE = 'report-only';
const isProd = process.env.NODE_ENV === 'production';

// NOTE: Next.js needs 'unsafe-inline' for its inline bootstrap scripts unless you use nonces
// (middleware/proxy). A nonce-based CSP is the only way to fully satisfy Lighthouse's
// "CSP effective against XSS" check, but it forces dynamic rendering — a real tradeoff.
// If you still use Google Fonts via <link>, add https://fonts.googleapis.com to style-src
// and https://fonts.gstatic.com to font-src (better: migrate to next/font and remove them).
const csp = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'" + (isProd ? '' : " 'unsafe-eval'"),
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "media-src 'self'",
  "font-src 'self' data:",
  "connect-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'self'",
].join('; ');

export default async function headers() {
  const security = [
    { key: 'X-Content-Type-Options', value: 'nosniff' },
    { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
    { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
    { key: 'Cross-Origin-Opener-Policy', value: 'same-origin' },
    { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
  ];
  // HSTS is ignored over plain http, and is sticky once the browser sees it over https.
  // No "preload" and no "includeSubDomains" on purpose — add them only when you're sure.
  if (isProd) security.push({ key: 'Strict-Transport-Security', value: 'max-age=31536000' });
  if (CSP_MODE === 'enforce') security.push({ key: 'Content-Security-Policy', value: csp });
  if (CSP_MODE === 'report-only') security.push({ key: 'Content-Security-Policy-Report-Only', value: csp });

  return [
    { source: '/:path*', headers: security },
    {
      // Unhashed files in /public: 30 days. If you replace a file, RENAME it (s1.webp -> s1.v2.webp)
      // or users will see the old one for up to 30 days.
      source: '/:all*(webp|avif|png|jpg|jpeg|gif|svg|ico|mp4|webm)',
      headers: [{ key: 'Cache-Control', value: 'public, max-age=2592000, stale-while-revalidate=86400' }],
    },
  ];
}
